Bridge.assembly("ConnectFour", function ($asm, globals) {
    "use strict";


    var $m = Bridge.setMetadata,
        $n = ["System","System.Collections.Generic","System.Threading.Tasks","ConnectFour"];
    $m("ConnectFour.Move", function () { return {"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"Index","t":16,"rt":$n[0].Int32,"g":{"a":2,"n":"get_Index","t":8,"rt":$n[0].Int32,"fg":"Index","box":function ($v) { return Bridge.box($v, System.Int32);}},"s":{"a":2,"n":"set_Index","t":8,"p":[$n[0].Int32],"rt":$n[0].Void,"fs":"Index"},"fn":"Index"},{"a":1,"backing":true,"n":"<Index>k__BackingField","t":4,"rt":$n[0].Int32,"sn":"Index","box":function ($v) { return Bridge.box($v, System.Int32);}}]}; }, $n);
    $m("ConnectFour.IController", function () { return {"att":160,"a":4,"m":[{"ab":true,"a":2,"n":"Select","t":8,"pi":[{"n":"moves","pt":$n[1].IEnumerable$1(ConnectFour.Move),"ps":0}],"sn":"ConnectFour$IController$Select","rt":$n[2].Task$1(ConnectFour.Move),"p":[$n[1].IEnumerable$1(ConnectFour.Move)]}]}; }, $n);
    $m("ConnectFour.SomeController", function () { return {"att":1048576,"a":4,"m":[{"a":2,"n":".ctor","t":1,"p":[$n[0].String],"pi":[{"n":"name","pt":$n[0].String,"ps":0}],"sn":"ctor"},{"a":2,"n":"ButtonClick","t":8,"pi":[{"n":"index","pt":$n[0].Int32,"ps":0}],"sn":"ButtonClick","rt":$n[0].Void,"p":[$n[0].Int32]},{"a":2,"n":"Select","t":8,"pi":[{"n":"moves","pt":$n[1].IEnumerable$1(ConnectFour.Move),"ps":0}],"sn":"Select","rt":$n[2].Task$1(ConnectFour.Move),"p":[$n[1].IEnumerable$1(ConnectFour.Move)]},{"a":1,"n":"b","t":4,"rt":$n[2].TaskCompletionSource,"sn":"b"},{"a":1,"n":"name","t":4,"rt":$n[0].String,"sn":"name","ro":true}]}; }, $n);
    $m("ConnectFour.Game", function () { return {"nested":[$n[3].Game.Chip],"att":1048576,"a":4,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":1,"n":"CheckForWin","t":8,"pi":[{"n":"m","pt":$n[3].Move,"ps":0}],"sn":"CheckForWin","rt":$n[0].Boolean,"p":[$n[3].Move],"box":function ($v) { return Bridge.box($v, System.Boolean, System.Boolean.toString);}},{"a":1,"n":"Row","t":8,"pi":[{"n":"row","pt":$n[0].Int32,"ps":0},{"n":"col","pt":$n[0].Int32,"ps":1},{"n":"drow","pt":$n[0].Int32,"ps":2},{"n":"dcol","pt":$n[0].Int32,"ps":3}],"sn":"Row","rt":$n[0].Boolean,"p":[$n[0].Int32,$n[0].Int32,$n[0].Int32,$n[0].Int32],"box":function ($v) { return Bridge.box($v, System.Boolean, System.Boolean.toString);}},{"a":2,"n":"Run","t":8,"sn":"Run","rt":$n[2].Task},{"a":2,"n":"Controller1","t":16,"rt":$n[3].IController,"g":{"a":2,"n":"get_Controller1","t":8,"rt":$n[3].IController,"fg":"Controller1"},"s":{"a":2,"n":"set_Controller1","t":8,"p":[$n[3].IController],"rt":$n[0].Void,"fs":"Controller1"},"fn":"Controller1"},{"a":2,"n":"Controller2","t":16,"rt":$n[3].IController,"g":{"a":2,"n":"get_Controller2","t":8,"rt":$n[3].IController,"fg":"Controller2"},"s":{"a":2,"n":"set_Controller2","t":8,"p":[$n[3].IController],"rt":$n[0].Void,"fs":"Controller2"},"fn":"Controller2"},{"a":2,"n":"chips","t":4,"rt":System.Array.type(ConnectFour.Game.Chip, 2),"sn":"chips"},{"a":1,"n":"cols","is":true,"t":4,"rt":$n[0].Int32,"sn":"cols","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":2,"n":"currentChip","t":4,"rt":$n[3].Game.Chip,"sn":"currentChip","box":function ($v) { return Bridge.box($v, ConnectFour.Game.Chip, System.Enum.toStringFn(ConnectFour.Game.Chip));}},{"a":1,"n":"rows","is":true,"t":4,"rt":$n[0].Int32,"sn":"rows","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":1,"n":"win","t":4,"rt":$n[0].Int32,"sn":"win","box":function ($v) { return Bridge.box($v, System.Int32);}},{"a":2,"n":"OnUpdate","t":2,"ad":{"a":2,"n":"add_OnUpdate","t":8,"pi":[{"n":"value","pt":Function,"ps":0}],"sn":"addOnUpdate","rt":$n[0].Void,"p":[Function]},"r":{"a":2,"n":"remove_OnUpdate","t":8,"pi":[{"n":"value","pt":Function,"ps":0}],"sn":"removeOnUpdate","rt":$n[0].Void,"p":[Function]}},{"a":1,"backing":true,"n":"<Controller1>k__BackingField","t":4,"rt":$n[3].IController,"sn":"Controller1"},{"a":1,"backing":true,"n":"<Controller2>k__BackingField","t":4,"rt":$n[3].IController,"sn":"Controller2"}]}; }, $n);
    $m("ConnectFour.Game.Chip", function () { return {"td":$n[3].Game,"att":258,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":2,"n":"C1","is":true,"t":4,"rt":$n[3].Game.Chip,"sn":"C1","box":function ($v) { return Bridge.box($v, ConnectFour.Game.Chip, System.Enum.toStringFn(ConnectFour.Game.Chip));}},{"a":2,"n":"C2","is":true,"t":4,"rt":$n[3].Game.Chip,"sn":"C2","box":function ($v) { return Bridge.box($v, ConnectFour.Game.Chip, System.Enum.toStringFn(ConnectFour.Game.Chip));}},{"a":2,"n":"NONE","is":true,"t":4,"rt":$n[3].Game.Chip,"sn":"NONE","box":function ($v) { return Bridge.box($v, ConnectFour.Game.Chip, System.Enum.toStringFn(ConnectFour.Game.Chip));}}]}; }, $n);
    $m("ConnectFour.Program", function () { return {"nested":[Function,Function],"att":1048577,"a":2,"m":[{"a":2,"isSynthetic":true,"n":".ctor","t":1,"sn":"ctor"},{"a":1,"n":"Game_OnUpdate","is":true,"t":8,"pi":[{"n":"game","pt":$n[3].Game,"ps":0}],"sn":"Game_OnUpdate","rt":$n[0].Void,"p":[$n[3].Game]},{"a":2,"n":"Main","is":true,"t":8,"sn":"Main","rt":$n[0].Void},{"a":1,"n":"canvas","is":true,"t":4,"rt":HTMLCanvasElement,"sn":"canvas"},{"a":1,"n":"Color","is":true,"t":2,"ad":{"a":1,"n":"add_Color","is":true,"t":8,"pi":[{"n":"value","pt":Function,"ps":0}],"sn":"addColor","rt":$n[0].Void,"p":[Function]},"r":{"a":1,"n":"remove_Color","is":true,"t":8,"pi":[{"n":"value","pt":Function,"ps":0}],"sn":"removeColor","rt":$n[0].Void,"p":[Function]}},{"a":1,"n":"Selection","is":true,"t":2,"ad":{"a":1,"n":"add_Selection","is":true,"t":8,"pi":[{"n":"value","pt":Function,"ps":0}],"sn":"addSelection","rt":$n[0].Void,"p":[Function]},"r":{"a":1,"n":"remove_Selection","is":true,"t":8,"pi":[{"n":"value","pt":Function,"ps":0}],"sn":"removeSelection","rt":$n[0].Void,"p":[Function]}}]}; }, $n);
    $m("ConnectFour.Version", function () { return {"att":1048960,"a":4,"s":true,"m":[{"a":2,"n":"Info","is":true,"t":4,"rt":$n[0].String,"sn":"Info"}]}; }, $n);
});
